from __future__ import annotations

import json
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import websocket

from .model import BANDS, validate_bands


@dataclass(frozen=True)
class AudioSettings:
    capture_device: str = "hw:Loopback,1,0"
    playback_device: str = "hw:Headphones,0"
    samplerate: int = 44100
    chunksize: int = 1024


def build_config(
    bands: dict[str, float], settings: AudioSettings = AudioSettings()
) -> dict[str, Any]:
    bands = validate_bands(bands)
    # Graphic EQ boosts can exceed digital full scale. This conservative,
    # invisible pre-gain preserves headroom without adding another UI control.
    headroom = -max(0.0, max(bands.values()))
    filters: dict[str, Any] = {
        "coldth_headroom": {
            "type": "Gain",
            "parameters": {"gain": headroom, "scale": "dB"},
        }
    }
    filter_names = ["coldth_headroom"]
    for frequency in BANDS:
        name = f"coldth_{frequency}"
        filters[name] = {
            "type": "Biquad",
            "parameters": {
                "type": "Peaking",
                "freq": float(frequency),
                "gain": bands[str(frequency)],
                "q": 1.4,
            },
        }
        filter_names.append(name)

    return {
        "title": "Coldth",
        "description": "Generated by Coldth. Edit EQ settings through the web UI.",
        "devices": {
            "samplerate": settings.samplerate,
            "chunksize": settings.chunksize,
            "target_level": settings.chunksize * 2,
            "adjust_period": 10,
            "enable_rate_adjust": True,
            "resampler": {"type": "AsyncSinc", "profile": "Balanced"},
            "capture": {
                "type": "Alsa",
                "channels": 2,
                "device": settings.capture_device,
                "format": "S16LE",
            },
            "playback": {
                "type": "Alsa",
                "channels": 2,
                "device": settings.playback_device,
                "format": "S32LE",
            },
        },
        "filters": filters,
        "pipeline": [{"type": "Filter", "channels": [0, 1], "names": filter_names}],
    }


class CamillaClient:
    def __init__(
        self,
        url: str,
        config_path: Path,
        settings: AudioSettings = AudioSettings(),
        timeout: float = 1.0,
    ):
        self.url = url
        self.config_path = config_path
        self.settings = settings
        self.timeout = timeout
        self._lock = threading.Lock()
        self._last_error: str | None = "Audio engine has not been contacted yet"
        self._last_apply_error: str | None = None

    def _command(self, command: Any) -> dict[str, Any]:
        with self._lock:
            connection = websocket.create_connection(self.url, timeout=self.timeout)
            try:
                connection.send(json.dumps(command))
                return json.loads(connection.recv())
            finally:
                connection.close()

    def apply(self, bands: dict[str, float]) -> bool:
        config = build_config(bands, self.settings)
        encoded = json.dumps(config, indent=2) + "\n"
        self.config_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self.config_path.with_suffix(".tmp")
        temporary.write_text(encoded, encoding="utf-8")
        temporary.replace(self.config_path)

        try:
            response = self._command({"SetConfigJson": json.dumps(config)})
            result = response.get("SetConfigJson", {}).get("result")
            if result != "Ok":
                raise RuntimeError(f"CamillaDSP rejected the configuration: {result}")
        except Exception as error:
            self._last_error = str(error)
            self._last_apply_error = str(error)
            return False
        self._last_error = None
        self._last_apply_error = None
        return True

    def status(self) -> dict[str, Any]:
        try:
            response = self._command("GetState")
            result = response.get("GetState", {})
            if result.get("result") != "Ok":
                raise RuntimeError(f"Unable to read CamillaDSP state: {result.get('result')}")
            self._last_error = None
            return {
                "online": True,
                "state": result.get("value"),
                "error": None,
                "apply_error": self._last_apply_error,
            }
        except Exception as error:
            self._last_error = str(error)
        return {
            "online": self._last_error is None,
            "error": self._last_error,
            "apply_error": self._last_apply_error,
        }

    def levels(self) -> dict[str, Any]:
        response = self._command("GetSignalLevels")
        result = response.get("GetSignalLevels", {})
        if result.get("result") != "Ok":
            raise RuntimeError(f"Unable to read signal levels: {result.get('result')}")
        value = result.get("value")
        if not isinstance(value, dict):
            raise RuntimeError("CamillaDSP returned invalid signal levels")
        return value


class PersistentCamillaClient:
    """Keep a websocket open so CamillaDSP can accumulate meter samples."""

    def __init__(self, url: str, timeout: float = 1.0):
        self.url = url
        self.timeout = timeout
        self._lock = threading.Lock()
        self._connection: websocket.WebSocket | None = None

    def _close_unlocked(self) -> None:
        if self._connection is not None:
            try:
                self._connection.close()
            finally:
                self._connection = None

    def close(self) -> None:
        with self._lock:
            self._close_unlocked()

    def command(self, command: Any) -> dict[str, Any]:
        with self._lock:
            try:
                if self._connection is None:
                    self._connection = websocket.create_connection(
                        self.url, timeout=self.timeout
                    )
                self._connection.send(json.dumps(command))
                return json.loads(self._connection.recv())
            except Exception:
                self._close_unlocked()
                raise


class SignalLevelClient:
    def __init__(self, url: str, timeout: float = 1.0):
        self._client = PersistentCamillaClient(url, timeout)

    def close(self) -> None:
        self._client.close()

    def levels(self) -> dict[str, Any]:
        response = self._client.command("GetSignalLevels")
        result = response.get("GetSignalLevels", {})
        if result.get("result") != "Ok":
            raise RuntimeError(f"Unable to read signal levels: {result.get('result')}")
        value = result.get("value")
        if not isinstance(value, dict):
            raise RuntimeError("CamillaDSP returned invalid signal levels")
        return value


class SpectrumClient:
    """Read an optional analyzer-only CamillaDSP instance."""

    def __init__(self, url: str, timeout: float = 0.35):
        self._client = PersistentCamillaClient(url, timeout)

    def close(self) -> None:
        self._client.close()

    def levels(self) -> list[float] | None:
        try:
            response = self._client.command("GetPlaybackSignalRms")
            result = response.get("GetPlaybackSignalRms", {})
            values = result.get("value") if result.get("result") == "Ok" else None
            if not isinstance(values, list) or len(values) != len(BANDS):
                return None
            return [float(value) for value in values]
        except Exception:
            return None
