from __future__ import annotations

import json
import math
import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import websocket

from .model import (
    BANDS,
    DEFAULT_PREAMP,
    validate_balance,
    validate_bands,
    validate_preamp,
)


@dataclass(frozen=True)
class AudioSettings:
    capture_device: str = "hw:Loopback,1,0"
    playback_device: str = "hw:Headphones,0"
    capture_format: str = "S16LE"
    playback_format: str = "S16LE"
    samplerate: int = 44100
    chunksize: int = 1024


def eq_response_db(
    bands: dict[str, float],
    frequencies: np.ndarray,
    samplerate: int,
    q: float = 1.4,
) -> np.ndarray:
    """Return Coldth's complete peaking-EQ response at the given frequencies."""
    frequencies = np.asarray(frequencies, dtype=np.float64)
    nyquist = samplerate / 2
    omega = 2 * np.pi * frequencies / samplerate
    z1 = np.exp(-1j * omega)
    z2 = z1 * z1
    response_db = np.zeros_like(frequencies)

    for frequency in BANDS:
        gain = bands[str(frequency)]
        if gain == 0 or frequency >= nyquist:
            continue

        amplitude = 10 ** (gain / 40)
        center = 2 * math.pi * frequency / samplerate
        alpha = math.sin(center) / (2 * q)
        b0 = 1 + alpha * amplitude
        b1 = -2 * math.cos(center)
        b2 = 1 - alpha * amplitude
        a0 = 1 + alpha / amplitude
        a1 = -2 * math.cos(center)
        a2 = 1 - alpha / amplitude
        response = (b0 + b1 * z1 + b2 * z2) / (a0 + a1 * z1 + a2 * z2)
        response_db += 20 * np.log10(np.maximum(np.abs(response), 1e-12))

    return response_db


def eq_spectrum_offsets(
    bands: dict[str, float],
    samplerate: int,
    preamp: float = DEFAULT_PREAMP,
) -> list[float]:
    """Approximate post-EQ analyzer offsets at Coldth's ten band centers."""
    preamp = validate_preamp(preamp)
    response = eq_response_db(
        bands,
        np.asarray(BANDS, dtype=np.float64),
        samplerate,
    )
    return [float(value + preamp) for value in response]


def build_config(
    bands: dict[str, float],
    settings: AudioSettings = AudioSettings(),
    balance: int = 0,
    preamp: float = DEFAULT_PREAMP,
) -> dict[str, Any]:
    bands = validate_bands(bands)
    balance = validate_balance(balance)
    preamp = validate_preamp(preamp)
    filters: dict[str, Any] = {
        "coldth_preamp": {
            "type": "Gain",
            "parameters": {"gain": preamp, "scale": "dB"},
        }
    }
    filter_names = ["coldth_preamp"]
    for frequency in BANDS:
        name = f"coldth_{frequency}"
        filters[name] = {
            "type": "Biquad",
            "parameters": {
                "type": "Peaking",
                "freq": float(frequency),
                "gain": bands[str(frequency)],
                "q": 1.4,
            },
        }
        filter_names.append(name)

    def attenuation(position: float) -> float:
        return round(20 * math.log10(max(1.0 - position, 0.00001)), 4)

    left_gain = attenuation(balance / 100) if balance > 0 else 0.0
    right_gain = attenuation(-balance / 100) if balance < 0 else 0.0
    filters["coldth_balance_left"] = {
        "type": "Gain",
        "parameters": {"gain": left_gain, "scale": "dB"},
    }
    filters["coldth_balance_right"] = {
        "type": "Gain",
        "parameters": {"gain": right_gain, "scale": "dB"},
    }

    return {
        "title": "Coldth",
        "description": "Generated by Coldth. Edit EQ settings through the web UI.",
        "devices": {
            "samplerate": settings.samplerate,
            "chunksize": settings.chunksize,
            "target_level": settings.chunksize * 2,
            "adjust_period": 10,
            "enable_rate_adjust": True,
            "resampler": {"type": "AsyncSinc", "profile": "Balanced"},
            "capture": {
                "type": "Alsa",
                "channels": 2,
                "device": settings.capture_device,
                "format": settings.capture_format,
            },
            "playback": {
                "type": "Alsa",
                "channels": 2,
                "device": settings.playback_device,
                "format": settings.playback_format,
            },
        },
        "filters": filters,
        "pipeline": [
            {"type": "Filter", "channels": [0, 1], "names": filter_names},
            {"type": "Filter", "channels": [0], "names": ["coldth_balance_left"]},
            {"type": "Filter", "channels": [1], "names": ["coldth_balance_right"]},
        ],
    }


class CamillaClient:
    def __init__(
        self,
        url: str,
        config_path: Path,
        settings: AudioSettings = AudioSettings(),
        timeout: float = 1.0,
    ):
        self.url = url
        self.config_path = config_path
        self.settings = settings
        self.timeout = timeout
        self._lock = threading.Lock()
        self._last_error: str | None = "Audio engine has not been contacted yet"
        self._last_apply_error: str | None = None

    def _command(self, command: Any) -> dict[str, Any]:
        with self._lock:
            connection = websocket.create_connection(self.url, timeout=self.timeout)
            try:
                connection.send(json.dumps(command))
                return json.loads(connection.recv())
            finally:
                connection.close()

    def apply(
        self,
        bands: dict[str, float],
        balance: int = 0,
        preamp: float = DEFAULT_PREAMP,
    ) -> bool:
        config = build_config(bands, self.settings, balance, preamp)
        encoded = json.dumps(config, indent=2) + "\n"
        self.config_path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self.config_path.with_suffix(".tmp")
        temporary.write_text(encoded, encoding="utf-8")
        temporary.replace(self.config_path)

        try:
            response = self._command({"SetConfigJson": json.dumps(config)})
            result = response.get("SetConfigJson", {}).get("result")
            if result != "Ok":
                raise RuntimeError(f"CamillaDSP rejected the configuration: {result}")
        except Exception as error:
            self._last_error = str(error)
            self._last_apply_error = str(error)
            return False
        self._last_error = None
        self._last_apply_error = None
        return True

    def status(self) -> dict[str, Any]:
        try:
            response = self._command("GetState")
            result = response.get("GetState", {})
            if result.get("result") != "Ok":
                raise RuntimeError(f"Unable to read CamillaDSP state: {result.get('result')}")
            state = result.get("value")
            online = state != "Inactive"
            state_error = (
                None
                if online
                else "CamillaDSP is inactive; its audio configuration did not start"
            )
            self._last_error = None
            return {
                "online": online,
                "state": state,
                "error": state_error,
                "apply_error": self._last_apply_error,
            }
        except Exception as error:
            self._last_error = str(error)
        return {
            "online": self._last_error is None,
            "error": self._last_error,
            "apply_error": self._last_apply_error,
        }

    def levels(self) -> dict[str, Any]:
        response = self._command("GetSignalLevels")
        result = response.get("GetSignalLevels", {})
        if result.get("result") != "Ok":
            raise RuntimeError(f"Unable to read signal levels: {result.get('result')}")
        value = result.get("value")
        if not isinstance(value, dict):
            raise RuntimeError("CamillaDSP returned invalid signal levels")
        return value

class PersistentCamillaClient:
    """Keep a websocket open so CamillaDSP can accumulate meter samples."""

    def __init__(self, url: str, timeout: float = 1.0):
        self.url = url
        self.timeout = timeout
        self._lock = threading.Lock()
        self._connection: websocket.WebSocket | None = None

    def _close_unlocked(self) -> None:
        if self._connection is not None:
            try:
                self._connection.close()
            finally:
                self._connection = None

    def close(self) -> None:
        with self._lock:
            self._close_unlocked()

    def command(self, command: Any) -> dict[str, Any]:
        with self._lock:
            try:
                if self._connection is None:
                    self._connection = websocket.create_connection(
                        self.url, timeout=self.timeout
                    )
                self._connection.send(json.dumps(command))
                return json.loads(self._connection.recv())
            except Exception:
                self._close_unlocked()
                raise


class SignalLevelClient:
    def __init__(self, url: str, timeout: float = 1.0):
        self._client = PersistentCamillaClient(url, timeout)

    def close(self) -> None:
        self._client.close()

    def levels(self) -> dict[str, Any]:
        response = self._client.command("GetSignalLevels")
        result = response.get("GetSignalLevels", {})
        if result.get("result") != "Ok":
            raise RuntimeError(f"Unable to read signal levels: {result.get('result')}")
        value = result.get("value")
        if not isinstance(value, dict):
            raise RuntimeError("CamillaDSP returned invalid signal levels")
        return value
